configuration:
  swagger:
    app: 'Library System 2.0'
    description: 'A simple library system built with Spring Boot'
    developer: 'Aldin Kovačević'
    email: 'aldin.kovacevic@ibu.edu.ba'

  mailsender:
    default: 'mailgun'

spring:
  data:
    mongodb:
      uri: mongodb+srv://aldin:GXst6r91aBaQzUHa@library.ymj4ft5.mongodb.net/?retryWrites=true&w=majority
      database: library-db

email:
  mailgun:
    domain: https://api.mailgun.net/v3/sandbox29278405945b4dc68ec56e4e841715a0.mailgun.org
    from-email: Library System <mailgun@sandbox29278405945b4dc68ec56e4e841715a0.mailgun.org>
    username: api
    password: b6ab4017ca3ca6bf54832afa11bd554e-3750a53b-1f515ec8

security:
  jwt:
    secret: 'mXLjT3Gm4skNsCdntWodbHPb1GqY35fGVaisLwImIp8cLZP7W6'

management:
  security:
    enabled: false